### PR TITLE
feat: Add eslint & flow.

### PR DESCRIPTION
**Pull request by hristoterezov**

### CODE REVIEW

**Comment by jmacelroy** [comment]
I'm no expert on the subject but I remember an effort to remove flow from our projects in favor of typescript? I guess this project is somewhat isolated from those other areas but I just wanted to make sure we made an attempt to be consistent with where we wanted to go in the future?

**Comment by jmacelroy** [comment]
I can't seem to approve the PR so I'm not sure if it's a repo setting missing or something wrong with my perms? Anyways, I approve but would like more info on why we use flow here for my education.

**Comment by hristoterezov** [comment]
@jmacelroy I'm not aware of this effort. I've heard some suggestions about it. Do we actually agree on that? Do we have  any projects that uses typescript?

Note I'm not against moving to typescript!

I'm not worried for consistency because as far as I know we don't have typescript projects (or at least I'm not aware that we have :) ). Also jitsi-meet, lib-jitsi-meet, jitsi-meet-electron, jitsi-meet-electron-utils and many many more don't have any typescript in them. So I'm not so worried about consistency. Of course if I missed something and this the direction we want to go probably we should work on that at some point.

**Comment by zbettenbuk** [comment]
@hristoterezov @jmacelroy there was no decision, but yes, there is an ongoing effort to move away from Flow and jump into TS, especially for new projects (we're not sure if meet will ever be converted to TS, it's just too much of a hassle).

If you're interested, here are a few repos that are already done with TS: https://github.com/jitsi?q=&type=&language=typescript

Most of them were done by me, but i'm no Ts expert by any means :)

**Pull request closed without merging**
